### ISSUE TITLE
TypeError: ngModuleType.\u0275mod is undefined

### ISSUE THREAD

**Issue by ShaunBrassell** [Leo1305Pineda/ion-media-cache#1]
Hi there!

Have tried to include your code in my Ionic 5 app, but having some issues. 

Initially it complained about a missing WebView, but a 'npm install @ionic-native/ionic-webview' fixed that.

Once I add the directive, I now get "TypeError: ngModuleType.\u0275mod is undefined."

I have tried install lodash and fs-web as I see you have those dependencies as well, but no joy just yet.

Thanks, Shaun

**Comment by ShaunBrassell** [comment]
I have sorted my issue, looks like a put the Webview into the child module, and not the app.module.ts as a provider!

**Comment by Leo1305Pineda** [comment]
Hi there Shaun Brassell
to use  !important
<div class="center-auth"  .... >
`.center-auth[_ngcontent-fqw-c113] {
    width: 100%;
    position: absolute;
    z-index: 2;
    height: 100%;
    background-repeat: no-repeat!important;
    background-size: cover!important;
    background-position: 50%!important;
}`
![image](https://user-images.githubusercontent.com/12752959/101823491-38453d80-3b01-11eb-808a-cbaadbbbd375.png)
