### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by dan-overton** [Leo1305Pineda/ion-media-cache#2]
Hi,

I'm wanting to use this code in a project, but really need the code to be licensed before I can include it. Could you please add a LICENSE file to the repo?

Happy to open a PR for it if that helps.

**Comment by Leo1305Pineda** [comment]
Hi Dan Overton
Ready
The license was added. test if you require the approval of a PR. Send it that I will gladly review it.

**Comment by dan-overton** [comment]
That's perfect, many thanks @Leo1305Pineda
