### ISSUE TITLE
cacheDirectoryName is hardcoded

### ISSUE THREAD

**Issue by ShaunBrassell** [Leo1305Pineda/ion-media-cache#4]
Hi there.

Thanks for the epic plugin, fantastic! Was looking to change the cacheDirectoryName but I see that it is hardcoded on line 62 in ion-media-cache.ts.

Guessing it should be:
this.cacheDirectoryName = o.cacheDirectoryName || 'ion-media-cache';

Cheers

**Comment by Leo1305Pineda** [comment]
Thanks already cacheDirectoryName property was updated.
`npm i ion-media-cache@latest`
